<?php
/**
 * LnrpcWalletBalanceResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Lnd\Rest\Model;

use \ArrayAccess;
use \Lnd\Rest\ObjectSerializer;

/**
 * LnrpcWalletBalanceResponse Class Doc Comment
 *
 * @category Class
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LnrpcWalletBalanceResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'lnrpcWalletBalanceResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'totalBalance' => 'string',
        'confirmedBalance' => 'string',
        'unconfirmedBalance' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'totalBalance' => 'int64',
        'confirmedBalance' => 'int64',
        'unconfirmedBalance' => 'int64'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'totalBalance' => 'total_balance',
        'confirmedBalance' => 'confirmed_balance',
        'unconfirmedBalance' => 'unconfirmed_balance'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'totalBalance' => 'setTotalBalance',
        'confirmedBalance' => 'setConfirmedBalance',
        'unconfirmedBalance' => 'setUnconfirmedBalance'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'totalBalance' => 'getTotalBalance',
        'confirmedBalance' => 'getConfirmedBalance',
        'unconfirmedBalance' => 'getUnconfirmedBalance'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['totalBalance'] = isset($data['totalBalance']) ? $data['totalBalance'] : null;
        $this->container['confirmedBalance'] = isset($data['confirmedBalance']) ? $data['confirmedBalance'] : null;
        $this->container['unconfirmedBalance'] = isset($data['unconfirmedBalance']) ? $data['unconfirmedBalance'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets totalBalance
     *
     * @return string
     */
    public function getTotalBalance()
    {
        return $this->container['totalBalance'];
    }

    /**
     * Sets totalBalance
     *
     * @param string $totalBalance totalBalance
     *
     * @return $this
     */
    public function setTotalBalance($totalBalance)
    {
        $this->container['totalBalance'] = $totalBalance;

        return $this;
    }

    /**
     * Gets confirmedBalance
     *
     * @return string
     */
    public function getConfirmedBalance()
    {
        return $this->container['confirmedBalance'];
    }

    /**
     * Sets confirmedBalance
     *
     * @param string $confirmedBalance confirmedBalance
     *
     * @return $this
     */
    public function setConfirmedBalance($confirmedBalance)
    {
        $this->container['confirmedBalance'] = $confirmedBalance;

        return $this;
    }

    /**
     * Gets unconfirmedBalance
     *
     * @return string
     */
    public function getUnconfirmedBalance()
    {
        return $this->container['unconfirmedBalance'];
    }

    /**
     * Sets unconfirmedBalance
     *
     * @param string $unconfirmedBalance unconfirmedBalance
     *
     * @return $this
     */
    public function setUnconfirmedBalance($unconfirmedBalance)
    {
        $this->container['unconfirmedBalance'] = $unconfirmedBalance;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


