<?php
/**
 * LnrpcSendManyRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Lnd\Rest\Model;

use \ArrayAccess;
use \Lnd\Rest\ObjectSerializer;

/**
 * LnrpcSendManyRequest Class Doc Comment
 *
 * @category Class
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LnrpcSendManyRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'lnrpcSendManyRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'addrToAmount' => 'map[string,string]',
        'targetConf' => 'int',
        'satPerVbyte' => 'string',
        'satPerByte' => 'string',
        'label' => 'string',
        'minConfs' => 'int',
        'spendUnconfirmed' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'addrToAmount' => 'int64',
        'targetConf' => 'int32',
        'satPerVbyte' => 'uint64',
        'satPerByte' => 'int64',
        'label' => null,
        'minConfs' => 'int32',
        'spendUnconfirmed' => 'boolean'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'addrToAmount' => 'AddrToAmount',
        'targetConf' => 'target_conf',
        'satPerVbyte' => 'sat_per_vbyte',
        'satPerByte' => 'sat_per_byte',
        'label' => 'label',
        'minConfs' => 'min_confs',
        'spendUnconfirmed' => 'spend_unconfirmed'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'addrToAmount' => 'setAddrToAmount',
        'targetConf' => 'setTargetConf',
        'satPerVbyte' => 'setSatPerVbyte',
        'satPerByte' => 'setSatPerByte',
        'label' => 'setLabel',
        'minConfs' => 'setMinConfs',
        'spendUnconfirmed' => 'setSpendUnconfirmed'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'addrToAmount' => 'getAddrToAmount',
        'targetConf' => 'getTargetConf',
        'satPerVbyte' => 'getSatPerVbyte',
        'satPerByte' => 'getSatPerByte',
        'label' => 'getLabel',
        'minConfs' => 'getMinConfs',
        'spendUnconfirmed' => 'getSpendUnconfirmed'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['addrToAmount'] = isset($data['addrToAmount']) ? $data['addrToAmount'] : null;
        $this->container['targetConf'] = isset($data['targetConf']) ? $data['targetConf'] : null;
        $this->container['satPerVbyte'] = isset($data['satPerVbyte']) ? $data['satPerVbyte'] : null;
        $this->container['satPerByte'] = isset($data['satPerByte']) ? $data['satPerByte'] : null;
        $this->container['label'] = isset($data['label']) ? $data['label'] : null;
        $this->container['minConfs'] = isset($data['minConfs']) ? $data['minConfs'] : null;
        $this->container['spendUnconfirmed'] = isset($data['spendUnconfirmed']) ? $data['spendUnconfirmed'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets addrToAmount
     *
     * @return map[string,string]
     */
    public function getAddrToAmount()
    {
        return $this->container['addrToAmount'];
    }

    /**
     * Sets addrToAmount
     *
     * @param map[string,string] $addrToAmount addrToAmount
     *
     * @return $this
     */
    public function setAddrToAmount($addrToAmount)
    {
        $this->container['addrToAmount'] = $addrToAmount;

        return $this;
    }

    /**
     * Gets targetConf
     *
     * @return int
     */
    public function getTargetConf()
    {
        return $this->container['targetConf'];
    }

    /**
     * Sets targetConf
     *
     * @param int $targetConf The target number of blocks that this transaction should be confirmed by.
     *
     * @return $this
     */
    public function setTargetConf($targetConf)
    {
        $this->container['targetConf'] = $targetConf;

        return $this;
    }

    /**
     * Gets satPerVbyte
     *
     * @return string
     */
    public function getSatPerVbyte()
    {
        return $this->container['satPerVbyte'];
    }

    /**
     * Sets satPerVbyte
     *
     * @param string $satPerVbyte A manual fee rate set in sat/vbyte that should be used when crafting the transaction.
     *
     * @return $this
     */
    public function setSatPerVbyte($satPerVbyte)
    {
        $this->container['satPerVbyte'] = $satPerVbyte;

        return $this;
    }

    /**
     * Gets satPerByte
     *
     * @return string
     */
    public function getSatPerByte()
    {
        return $this->container['satPerByte'];
    }

    /**
     * Sets satPerByte
     *
     * @param string $satPerByte Deprecated, use sat_per_vbyte. A manual fee rate set in sat/vbyte that should be used when crafting the transaction.
     *
     * @return $this
     */
    public function setSatPerByte($satPerByte)
    {
        $this->container['satPerByte'] = $satPerByte;

        return $this;
    }

    /**
     * Gets label
     *
     * @return string
     */
    public function getLabel()
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param string $label An optional label for the transaction, limited to 500 characters.
     *
     * @return $this
     */
    public function setLabel($label)
    {
        $this->container['label'] = $label;

        return $this;
    }

    /**
     * Gets minConfs
     *
     * @return int
     */
    public function getMinConfs()
    {
        return $this->container['minConfs'];
    }

    /**
     * Sets minConfs
     *
     * @param int $minConfs The minimum number of confirmations each one of your outputs used for the transaction must satisfy.
     *
     * @return $this
     */
    public function setMinConfs($minConfs)
    {
        $this->container['minConfs'] = $minConfs;

        return $this;
    }

    /**
     * Gets spendUnconfirmed
     *
     * @return bool
     */
    public function getSpendUnconfirmed()
    {
        return $this->container['spendUnconfirmed'];
    }

    /**
     * Sets spendUnconfirmed
     *
     * @param bool $spendUnconfirmed Whether unconfirmed outputs should be used as inputs for the transaction.
     *
     * @return $this
     */
    public function setSpendUnconfirmed($spendUnconfirmed)
    {
        $this->container['spendUnconfirmed'] = $spendUnconfirmed;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


