<?php
/**
 * LnrpcCommitmentType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Lnd\Rest\Model;
use \Lnd\Rest\ObjectSerializer;

/**
 * LnrpcCommitmentType Class Doc Comment
 *
 * @category Class
 * @description - LEGACY: A channel using the legacy commitment format having tweaked to_remote keys.  - STATIC_REMOTE_KEY: A channel that uses the modern commitment format where the key in the output of the remote party does not change each state. This makes back up and recovery easier as when the channel is closed, the funds go directly to that key.  - ANCHORS: A channel that uses a commitment format that has anchor outputs on the commitments, allowing fee bumping after a force close transaction has been broadcast.  - UNKNOWN_COMMITMENT_TYPE: Returned when the commitment type isn&#39;t known or unavailable.
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LnrpcCommitmentType
{
    /**
     * Possible values of this enum
     */
    const LEGACY = 'LEGACY';
    const STATIC_REMOTE_KEY = 'STATIC_REMOTE_KEY';
    const ANCHORS = 'ANCHORS';
    const UNKNOWN_COMMITMENT_TYPE = 'UNKNOWN_COMMITMENT_TYPE';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::LEGACY,
            self::STATIC_REMOTE_KEY,
            self::ANCHORS,
            self::UNKNOWN_COMMITMENT_TYPE,
        ];
    }
}


