<?php
/**
 * LnrpcChannelAcceptResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Lnd\Rest;

/**
 * LnrpcChannelAcceptResponseTest Class Doc Comment
 *
 * @category    Class
 * @description LnrpcChannelAcceptResponse
 * @package     Lnd\Rest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LnrpcChannelAcceptResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LnrpcChannelAcceptResponse"
     */
    public function testLnrpcChannelAcceptResponse()
    {
    }

    /**
     * Test attribute "accept"
     */
    public function testPropertyAccept()
    {
    }

    /**
     * Test attribute "pendingChanId"
     */
    public function testPropertyPendingChanId()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }

    /**
     * Test attribute "upfrontShutdown"
     */
    public function testPropertyUpfrontShutdown()
    {
    }

    /**
     * Test attribute "csvDelay"
     */
    public function testPropertyCsvDelay()
    {
    }

    /**
     * Test attribute "reserveSat"
     */
    public function testPropertyReserveSat()
    {
    }

    /**
     * Test attribute "inFlightMaxMsat"
     */
    public function testPropertyInFlightMaxMsat()
    {
    }

    /**
     * Test attribute "maxHtlcCount"
     */
    public function testPropertyMaxHtlcCount()
    {
    }

    /**
     * Test attribute "minHtlcIn"
     */
    public function testPropertyMinHtlcIn()
    {
    }

    /**
     * Test attribute "minAcceptDepth"
     */
    public function testPropertyMinAcceptDepth()
    {
    }
}
