<?php
/**
 * LnrpcClosedChannelUpdateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Lnd\Rest;

/**
 * LnrpcClosedChannelUpdateTest Class Doc Comment
 *
 * @category    Class
 * @description LnrpcClosedChannelUpdate
 * @package     Lnd\Rest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LnrpcClosedChannelUpdateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LnrpcClosedChannelUpdate"
     */
    public function testLnrpcClosedChannelUpdate()
    {
    }

    /**
     * Test attribute "chanId"
     */
    public function testPropertyChanId()
    {
    }

    /**
     * Test attribute "capacity"
     */
    public function testPropertyCapacity()
    {
    }

    /**
     * Test attribute "closedHeight"
     */
    public function testPropertyClosedHeight()
    {
    }

    /**
     * Test attribute "chanPoint"
     */
    public function testPropertyChanPoint()
    {
    }
}
