<?php
/**
 * LnrpcResolutionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Lnd\Rest;

/**
 * LnrpcResolutionTest Class Doc Comment
 *
 * @category    Class
 * @description LnrpcResolution
 * @package     Lnd\Rest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LnrpcResolutionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LnrpcResolution"
     */
    public function testLnrpcResolution()
    {
    }

    /**
     * Test attribute "resolutionType"
     */
    public function testPropertyResolutionType()
    {
    }

    /**
     * Test attribute "outcome"
     */
    public function testPropertyOutcome()
    {
    }

    /**
     * Test attribute "outpoint"
     */
    public function testPropertyOutpoint()
    {
    }

    /**
     * Test attribute "amountSat"
     */
    public function testPropertyAmountSat()
    {
    }

    /**
     * Test attribute "sweepTxid"
     */
    public function testPropertySweepTxid()
    {
    }
}
