<?php
/**
 * LnrpcSendRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Lnd\Rest;

/**
 * LnrpcSendRequestTest Class Doc Comment
 *
 * @category    Class
 * @description LnrpcSendRequest
 * @package     Lnd\Rest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LnrpcSendRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LnrpcSendRequest"
     */
    public function testLnrpcSendRequest()
    {
    }

    /**
     * Test attribute "dest"
     */
    public function testPropertyDest()
    {
    }

    /**
     * Test attribute "destString"
     */
    public function testPropertyDestString()
    {
    }

    /**
     * Test attribute "amt"
     */
    public function testPropertyAmt()
    {
    }

    /**
     * Test attribute "paymentHash"
     */
    public function testPropertyPaymentHash()
    {
    }

    /**
     * Test attribute "paymentHashString"
     */
    public function testPropertyPaymentHashString()
    {
    }

    /**
     * Test attribute "paymentRequest"
     */
    public function testPropertyPaymentRequest()
    {
    }

    /**
     * Test attribute "finalCltvDelta"
     */
    public function testPropertyFinalCltvDelta()
    {
    }

    /**
     * Test attribute "feeLimit"
     */
    public function testPropertyFeeLimit()
    {
    }

    /**
     * Test attribute "outgoingChanId"
     */
    public function testPropertyOutgoingChanId()
    {
    }

    /**
     * Test attribute "cltvLimit"
     */
    public function testPropertyCltvLimit()
    {
    }

    /**
     * Test attribute "destTlv"
     */
    public function testPropertyDestTlv()
    {
    }
}
