<?php
/**
 * LnrpcNetworkInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Lnd\Rest;

/**
 * LnrpcNetworkInfoTest Class Doc Comment
 *
 * @category    Class
 * @description LnrpcNetworkInfo
 * @package     Lnd\Rest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LnrpcNetworkInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LnrpcNetworkInfo"
     */
    public function testLnrpcNetworkInfo()
    {
    }

    /**
     * Test attribute "graphDiameter"
     */
    public function testPropertyGraphDiameter()
    {
    }

    /**
     * Test attribute "avgOutDegree"
     */
    public function testPropertyAvgOutDegree()
    {
    }

    /**
     * Test attribute "maxOutDegree"
     */
    public function testPropertyMaxOutDegree()
    {
    }

    /**
     * Test attribute "numNodes"
     */
    public function testPropertyNumNodes()
    {
    }

    /**
     * Test attribute "numChannels"
     */
    public function testPropertyNumChannels()
    {
    }

    /**
     * Test attribute "totalNetworkCapacity"
     */
    public function testPropertyTotalNetworkCapacity()
    {
    }

    /**
     * Test attribute "avgChannelSize"
     */
    public function testPropertyAvgChannelSize()
    {
    }

    /**
     * Test attribute "minChannelSize"
     */
    public function testPropertyMinChannelSize()
    {
    }

    /**
     * Test attribute "maxChannelSize"
     */
    public function testPropertyMaxChannelSize()
    {
    }

    /**
     * Test attribute "medianChannelSizeSat"
     */
    public function testPropertyMedianChannelSizeSat()
    {
    }

    /**
     * Test attribute "numZombieChans"
     */
    public function testPropertyNumZombieChans()
    {
    }
}
