<?php
/**
 * LnrpcSendManyRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Lnd\Rest;

/**
 * LnrpcSendManyRequestTest Class Doc Comment
 *
 * @category    Class
 * @description LnrpcSendManyRequest
 * @package     Lnd\Rest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LnrpcSendManyRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LnrpcSendManyRequest"
     */
    public function testLnrpcSendManyRequest()
    {
    }

    /**
     * Test attribute "addrToAmount"
     */
    public function testPropertyAddrToAmount()
    {
    }

    /**
     * Test attribute "targetConf"
     */
    public function testPropertyTargetConf()
    {
    }

    /**
     * Test attribute "satPerVbyte"
     */
    public function testPropertySatPerVbyte()
    {
    }

    /**
     * Test attribute "satPerByte"
     */
    public function testPropertySatPerByte()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }

    /**
     * Test attribute "minConfs"
     */
    public function testPropertyMinConfs()
    {
    }

    /**
     * Test attribute "spendUnconfirmed"
     */
    public function testPropertySpendUnconfirmed()
    {
    }
}
