<?php
/**
 * LnrpcGetInfoResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Lnd\Rest;

/**
 * LnrpcGetInfoResponseTest Class Doc Comment
 *
 * @category    Class
 * @description LnrpcGetInfoResponse
 * @package     Lnd\Rest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LnrpcGetInfoResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LnrpcGetInfoResponse"
     */
    public function testLnrpcGetInfoResponse()
    {
    }

    /**
     * Test attribute "identityPubkey"
     */
    public function testPropertyIdentityPubkey()
    {
    }

    /**
     * Test attribute "alias"
     */
    public function testPropertyAlias()
    {
    }

    /**
     * Test attribute "numPendingChannels"
     */
    public function testPropertyNumPendingChannels()
    {
    }

    /**
     * Test attribute "numActiveChannels"
     */
    public function testPropertyNumActiveChannels()
    {
    }

    /**
     * Test attribute "numPeers"
     */
    public function testPropertyNumPeers()
    {
    }

    /**
     * Test attribute "blockHeight"
     */
    public function testPropertyBlockHeight()
    {
    }

    /**
     * Test attribute "blockHash"
     */
    public function testPropertyBlockHash()
    {
    }

    /**
     * Test attribute "syncedToChain"
     */
    public function testPropertySyncedToChain()
    {
    }

    /**
     * Test attribute "testnet"
     */
    public function testPropertyTestnet()
    {
    }

    /**
     * Test attribute "uris"
     */
    public function testPropertyUris()
    {
    }

    /**
     * Test attribute "bestHeaderTimestamp"
     */
    public function testPropertyBestHeaderTimestamp()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "numInactiveChannels"
     */
    public function testPropertyNumInactiveChannels()
    {
    }

    /**
     * Test attribute "chains"
     */
    public function testPropertyChains()
    {
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
    }

    /**
     * Test attribute "syncedToGraph"
     */
    public function testPropertySyncedToGraph()
    {
    }
}
