<?php
/**
 * LnrpcChannelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Lnd\Rest;

/**
 * LnrpcChannelTest Class Doc Comment
 *
 * @category    Class
 * @description LnrpcChannel
 * @package     Lnd\Rest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LnrpcChannelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LnrpcChannel"
     */
    public function testLnrpcChannel()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "remotePubkey"
     */
    public function testPropertyRemotePubkey()
    {
    }

    /**
     * Test attribute "channelPoint"
     */
    public function testPropertyChannelPoint()
    {
    }

    /**
     * Test attribute "chanId"
     */
    public function testPropertyChanId()
    {
    }

    /**
     * Test attribute "capacity"
     */
    public function testPropertyCapacity()
    {
    }

    /**
     * Test attribute "localBalance"
     */
    public function testPropertyLocalBalance()
    {
    }

    /**
     * Test attribute "remoteBalance"
     */
    public function testPropertyRemoteBalance()
    {
    }

    /**
     * Test attribute "commitFee"
     */
    public function testPropertyCommitFee()
    {
    }

    /**
     * Test attribute "commitWeight"
     */
    public function testPropertyCommitWeight()
    {
    }

    /**
     * Test attribute "feePerKw"
     */
    public function testPropertyFeePerKw()
    {
    }

    /**
     * Test attribute "unsettledBalance"
     */
    public function testPropertyUnsettledBalance()
    {
    }

    /**
     * Test attribute "totalSatoshisSent"
     */
    public function testPropertyTotalSatoshisSent()
    {
    }

    /**
     * Test attribute "totalSatoshisReceived"
     */
    public function testPropertyTotalSatoshisReceived()
    {
    }

    /**
     * Test attribute "numUpdates"
     */
    public function testPropertyNumUpdates()
    {
    }

    /**
     * Test attribute "pendingHtlcs"
     */
    public function testPropertyPendingHtlcs()
    {
    }

    /**
     * Test attribute "csvDelay"
     */
    public function testPropertyCsvDelay()
    {
    }

    /**
     * Test attribute "private"
     */
    public function testPropertyPrivate()
    {
    }

    /**
     * Test attribute "initiator"
     */
    public function testPropertyInitiator()
    {
    }

    /**
     * Test attribute "chanStatusFlags"
     */
    public function testPropertyChanStatusFlags()
    {
    }

    /**
     * Test attribute "localChanReserveSat"
     */
    public function testPropertyLocalChanReserveSat()
    {
    }

    /**
     * Test attribute "remoteChanReserveSat"
     */
    public function testPropertyRemoteChanReserveSat()
    {
    }

    /**
     * Test attribute "staticRemoteKey"
     */
    public function testPropertyStaticRemoteKey()
    {
    }
}
