<?php
/**
 * LnrpcChannelEdgeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Lnd\Rest;

/**
 * LnrpcChannelEdgeTest Class Doc Comment
 *
 * @category    Class
 * @description * A fully authenticated channel along with all its unique attributes. Once an authenticated channel announcement has been processed on the network, then an instance of ChannelEdgeInfo encapsulating the channels attributes is stored. The other portions relevant to routing policy of a channel are stored within a ChannelEdgePolicy for each direction of the channel.
 * @package     Lnd\Rest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LnrpcChannelEdgeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LnrpcChannelEdge"
     */
    public function testLnrpcChannelEdge()
    {
    }

    /**
     * Test attribute "channelId"
     */
    public function testPropertyChannelId()
    {
    }

    /**
     * Test attribute "chanPoint"
     */
    public function testPropertyChanPoint()
    {
    }

    /**
     * Test attribute "lastUpdate"
     */
    public function testPropertyLastUpdate()
    {
    }

    /**
     * Test attribute "node1Pub"
     */
    public function testPropertyNode1Pub()
    {
    }

    /**
     * Test attribute "node2Pub"
     */
    public function testPropertyNode2Pub()
    {
    }

    /**
     * Test attribute "capacity"
     */
    public function testPropertyCapacity()
    {
    }

    /**
     * Test attribute "node1Policy"
     */
    public function testPropertyNode1Policy()
    {
    }

    /**
     * Test attribute "node2Policy"
     */
    public function testPropertyNode2Policy()
    {
    }
}
