<?php
/**
 * LnrpcPaymentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Lnd\Rest;

/**
 * LnrpcPaymentTest Class Doc Comment
 *
 * @category    Class
 * @description LnrpcPayment
 * @package     Lnd\Rest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LnrpcPaymentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LnrpcPayment"
     */
    public function testLnrpcPayment()
    {
    }

    /**
     * Test attribute "paymentHash"
     */
    public function testPropertyPaymentHash()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "creationDate"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
    }

    /**
     * Test attribute "fee"
     */
    public function testPropertyFee()
    {
    }

    /**
     * Test attribute "paymentPreimage"
     */
    public function testPropertyPaymentPreimage()
    {
    }

    /**
     * Test attribute "valueSat"
     */
    public function testPropertyValueSat()
    {
    }

    /**
     * Test attribute "valueMsat"
     */
    public function testPropertyValueMsat()
    {
    }

    /**
     * Test attribute "paymentRequest"
     */
    public function testPropertyPaymentRequest()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "feeSat"
     */
    public function testPropertyFeeSat()
    {
    }

    /**
     * Test attribute "feeMsat"
     */
    public function testPropertyFeeMsat()
    {
    }
}
