<?php
/**
 * LnrpcInvoiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Lnd\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Lnd\Rest;

/**
 * LnrpcInvoiceTest Class Doc Comment
 *
 * @category    Class
 * @description LnrpcInvoice
 * @package     Lnd\Rest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LnrpcInvoiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LnrpcInvoice"
     */
    public function testLnrpcInvoice()
    {
    }

    /**
     * Test attribute "memo"
     */
    public function testPropertyMemo()
    {
    }

    /**
     * Test attribute "receipt"
     */
    public function testPropertyReceipt()
    {
    }

    /**
     * Test attribute "rPreimage"
     */
    public function testPropertyRPreimage()
    {
    }

    /**
     * Test attribute "rHash"
     */
    public function testPropertyRHash()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "settled"
     */
    public function testPropertySettled()
    {
    }

    /**
     * Test attribute "creationDate"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "settleDate"
     */
    public function testPropertySettleDate()
    {
    }

    /**
     * Test attribute "paymentRequest"
     */
    public function testPropertyPaymentRequest()
    {
    }

    /**
     * Test attribute "descriptionHash"
     */
    public function testPropertyDescriptionHash()
    {
    }

    /**
     * Test attribute "expiry"
     */
    public function testPropertyExpiry()
    {
    }

    /**
     * Test attribute "fallbackAddr"
     */
    public function testPropertyFallbackAddr()
    {
    }

    /**
     * Test attribute "cltvExpiry"
     */
    public function testPropertyCltvExpiry()
    {
    }

    /**
     * Test attribute "routeHints"
     */
    public function testPropertyRouteHints()
    {
    }

    /**
     * Test attribute "private"
     */
    public function testPropertyPrivate()
    {
    }

    /**
     * Test attribute "addIndex"
     */
    public function testPropertyAddIndex()
    {
    }

    /**
     * Test attribute "settleIndex"
     */
    public function testPropertySettleIndex()
    {
    }

    /**
     * Test attribute "amtPaid"
     */
    public function testPropertyAmtPaid()
    {
    }

    /**
     * Test attribute "amtPaidSat"
     */
    public function testPropertyAmtPaidSat()
    {
    }

    /**
     * Test attribute "amtPaidMsat"
     */
    public function testPropertyAmtPaidMsat()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "htlcs"
     */
    public function testPropertyHtlcs()
    {
    }
}
